package mmu.fyp.evoting.gui;

import mmu.fyp.evoting.crypto.eoltaa.EOLTAA;

/**
 * A registration request submitted by a voter and awaiting the CA's decision.
 * The pair (name, icNumber) is the voter's real-world identity claim; the CA
 * verifies it against its {@link CitizenRegistry} before allocating a
 * position in the EOLTAA voter directory.
 *
 * <p>The EOLTAA user keypair is generated by the system at submission time on
 * the voter's behalf so the voter does not have to manage cryptographic
 * material themselves — only the public key ever leaves the CA.
 *
 * @param name        voter's declared full name
 * @param icNumber    voter's declared IC number (normalised, no dashes)
 * @param credentials EOLTAA user keypair generated for this voter at submission time
 * @param submittedAt epoch ms when the request was submitted
 */
public record PendingRegistration(
        String name,
        String icNumber,
        EOLTAA.UserKeyPair credentials,
        long submittedAt) {

    /** The unique identifier used inside the CA registry. We use the IC number. */
    public String identity() { return icNumber; }

    /** "Name (IC: 890101-01-1234)" — for log lines and table cells. */
    public String displayLabel() {
        return name + " (IC: " + new CitizenRecord(name, icNumber).displayIc() + ")";
    }
}
